/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "success": "#2fe378",
        "warning": "#f59e0b",
        "info": "#3b82f6",
        "secondary": "#5f5e5e",
        "inverse-on-surface": "#eaf3e7",
        "on-tertiary-fixed": "#0b1c30",
        "primary-fixed-dim": "#2fe378",
        "inverse-primary": "#2fe378",
        "surface-tint": "#006d34",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf6ea",
        "primary": "#006d34",
        "primary-container": "#00d26a",
        "tertiary-container": "#a8b8d1",
        "secondary-container": "#e5e2e1",
        "on-primary-container": "#005426",
        "surface-variant": "#dce5d9",
        "on-tertiary": "#ffffff",
        "background": "#f3fcef",
        "on-primary-fixed-variant": "#005226",
        "surface-dim": "#d3ddd1",
        "primary-fixed": "#62ff95",
        "on-secondary-fixed": "#1c1b1b",
        "secondary-fixed": "#e5e2e1",
        "on-background": "#151e16",
        "surface-container": "#e7f1e4",
        "on-primary-fixed": "#00210b",
        "on-secondary-container": "#656464",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e1ebdf",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-highest": "#dce5d9",
        "inverse-surface": "#2a332a",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-tertiary-container": "#39495e",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface-bright": "#f3fcef",
        "tertiary-fixed": "#d3e4fe",
        "on-surface": "#151e16",
        "on-primary": "#ffffff",
        "outline-variant": "#bbcbba",
        "surface": "#f3fcef",
        "tertiary": "#505f76",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#6c7b6c",
        "on-secondary-fixed-variant": "#474646",
        "on-surface-variant": "#3c4a3d"
      },
      spacing: {
        "3xl": "64px",
        "lg": "24px",
        "base": "4px",
        "2xl": "48px",
        "margin-mobile": "16px",
        "xs": "4px",
        "md": "16px",
        "sm": "8px",
        "gutter": "16px",
        "margin-desktop": "32px",
        "xl": "32px"
      },
    },
    fontFamily: {
      cairo: ["Cairo", "system-ui", "sans-serif"],
    },
  },
  plugins: [],
};